// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xMj7SZoRtWtI2QRJJCBcOHHVKk8K-bc',
    appId: '1:1000949694569:web:2429632bfc9b1a752aa2f8',
    messagingSenderId: '1000949694569',
    projectId: 'chatapp-b0388',
    authDomain: 'chatapp-b0388.firebaseapp.com',
    storageBucket: 'chatapp-b0388.appspot.com',
    measurementId: 'G-GPDTCYV2X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgOePa3NKuNl9AXXeH9nfQ4g1phAFJl6k',
    appId: '1:1000949694569:android:7e570afbaa7454702aa2f8',
    messagingSenderId: '1000949694569',
    projectId: 'chatapp-b0388',
    storageBucket: 'chatapp-b0388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8K6mtobjHY5ORE5R5mJonb0aQcKFyo-c',
    appId: '1:1000949694569:ios:8a5ad8c5fc7f2ab52aa2f8',
    messagingSenderId: '1000949694569',
    projectId: 'chatapp-b0388',
    storageBucket: 'chatapp-b0388.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8K6mtobjHY5ORE5R5mJonb0aQcKFyo-c',
    appId: '1:1000949694569:ios:8a5ad8c5fc7f2ab52aa2f8',
    messagingSenderId: '1000949694569',
    projectId: 'chatapp-b0388',
    storageBucket: 'chatapp-b0388.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5xMj7SZoRtWtI2QRJJCBcOHHVKk8K-bc',
    appId: '1:1000949694569:web:8ec58121dac2e96d2aa2f8',
    messagingSenderId: '1000949694569',
    projectId: 'chatapp-b0388',
    authDomain: 'chatapp-b0388.firebaseapp.com',
    storageBucket: 'chatapp-b0388.appspot.com',
    measurementId: 'G-L6QDGPTFKG',
  );
}
